1. AttributeError: '_LazyConnection' object has no attribute 'connection'
   File "D:/python-liao/python-liao/www/transwarp/db11.py", line 96, in cleanup
   if self.connection:

    解决：line 79  : class _LazyConnection(object):  def __init(self):  ----> def __init__(self):

2. class _LazyConnection(object):   原db.py里_LazyConnection  是lasyConnection, 暂时不改

3.  AttributeError: 'NoneType' object has no attribute 'connect'
     File "D:/python-liao/python-liao/www/transwarp/db11.py", line 84, in cursor
      connection = engine.connect()

4.  File "D:/python-liao/python-liao/www/transwarp/db12.py", line 340, in update
    return _update(sql, *args)    此处不调用_update(sql, *args)
TypeError: 'NoneType' object is not callable

    解决：db12.py line: 175 装饰器return 语句缩进错误，应该提前

5. 函数内部的测试部分要保证缩进正常，否则报错如下：
 >>> select_int('select id from user where email=?', 'ada@test.org')
 **********************************************************************
1 items had failures:
   1 of  10 in __main__.select_int
***Test Failed*** 1 failures.



